server:
  port: 8081

spring:
  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qx_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  redis:
    port: 6379
    host: 192.168.157.128
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8  #最大空闲数
        min-idle: 0 #最小空闲连接
        max-wait: 100ms #连接等待时间

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)




